services:
  # Frontend service
  - type: web
    name: unified-form
    env: node
    buildCommand: |
      npm install
      npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://unified-form-backend.onrender.com
      - key: PORT
        value: 10000

  # Backend service
  - type: web
    name: unified-form-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api/schools
    autoDeploy: true 