services:
  # Frontend service
  - type: web
    name: unified-form-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://unified-form-backend.onrender.com
      - key: PORT
        value: 10000

  # Backend service
  - type: web
    name: unified-form-backend
    env: node
    buildCommand: |
      #!/bin/bash
      set -e
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      echo "Installing dependencies..."
      npm install
      echo "Creating dist directory..."
      mkdir -p dist/server
      echo "Building server..."
      npx tsc -p tsconfig.server.json
      echo "Checking build output..."
      ls -la dist/server || echo "dist/server directory not found"
      echo "Copying server files..."
      cp -r src/server/* dist/server/
      echo "Final directory structure:"
      find . -type f -name "*.js" | sort
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://unified-form-frontend.onrender.com
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        sync: false 