services:
  # Frontend service
  - type: web
    name: unified-form-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://unified-form-backend.onrender.com
      - key: PORT
        value: 10000

  # Backend service
  - type: web
    name: unified-form-backend
    env: node
    buildCommand: |
      npm install
      echo "Building server..."
      npm run build:server
      echo "Checking dist directory..."
      ls -la dist/server
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://unified-form-frontend.onrender.com
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        sync: false 